### ISSUE TITLE
Improve Sprint Reports display

### ISSUE THREAD

**Issue by dmukherjee** [rpt-labs/ghostbuster#48]
- [x] Display list of all milestone commit messages for the selected sprint
- [x] On student cards add capability to visually identify milestone commit messages (different color/ icon/ bold?)
- [x] Display total number of commits on the student card
- Instead of expanding, open a modal to display the list of all commit messages (Will address as a separate ticket #50)

**Comment by magee** [comment]
I like all but the last.  That means we can only see one student’s commits at a time.  The opportunity to open them and leave them open to see multiple students is helpful.  Let’s add a future ticket to consider making it user-configurable whether the open in place or via modal.

**Comment by dmukherjee** [comment]
Thanks for the feedback! I have added a separate ticket(#50) for the last item.

**Comment by dmukherjee** [comment]
resolved!
